### ISSUE TITLE
CUE timings are not highlighted when Cue Settings are included

### ISSUE THREAD

**Issue by bbgdzxng1** [spaceribs/vscode-webvtt-language#7]
Issue: The start/stop timings are not highlighted when CUE contains CUE Settings (aka positional data)

The issue is demonstrated when loading the following W3C snippet https://w3c.github.io/webvtt.js/parser.html

On line 3 `00:11.000 --> 00:13.000 vertical:rl`, the existence of `vertical:rl` causes the plugin not to highlight the start/stop CUE timings in VS Code in green.

```
WEBVTT

00:11.000 --> 00:13.000 vertical:rl
<v Roger Bingham>We are in New York City

00:13.000 --> 00:16.000
<v Roger Bingham>We're actually at the Lucern Hotel, just down the street

00:16.000 --> 00:18.000
<v Roger Bingham>from the American Museum of Natural History

00:18.000 --> 00:20.000
<v Roger Bingham>And with me is Neil deGrasse Tyson

00:20.000 --> 00:22.000
<v Roger Bingham>Astrophysicist, Director of the Hayden Planetarium
```

Test case: Remove `vertical:rl` and the syntax is correctly highlighted in VS Code.

Very cool tool, thanks @spaceribs.  I'm just migrating from Atom to VS Code and your VTT language parser is great.  I am logging the issue for reference in case you were not aware.

**Comment by spaceribs** [comment]
Thanks @bbgdzxng1, i'm putting up a fix for this now 👍

**Comment by bbgdzxng1** [comment]
Super cool @spaceribs.  Confirming that the update has already rippled its way through to my VSCode.  Thank-you so much for an excellent plugin.
